x-meltano-image: &meltano-image
  image: meltano-banvic:latest

  build: .

x-meltano-env: &meltano-env
  MELTANO_DATABASE_URI: postgresql://postgres:postgres@meltano-system-db/meltano


services:
  meltano:
    container_name: meltano # Persistir nome do container
    <<: *meltano-image
    command: dragon
    environment:
      <<: *meltano-env


    volumes:
      - meltano_elt_logs_data:/project/.meltano/logs/elt
      - ./load/data:/project/load/data
      - ./extract/data:/project/extract/data

    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - meltano-system-db
    networks:
      - meltano
      - banvicnet
      - indicium
    restart: unless-stopped

  meltano-system-db:
    container_name: meltano-system-db # Persistir nome do container
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: meltano
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - meltano_postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - meltano
    restart: unless-stopped

  
networks:
  meltano:
  banvicnet:
    external: true # LINKA MELTANO AO POSTGRE DO BANVIC
  indicium: 
    external: true # LINKA MELTANO AO POSTGRE DO WAREHOUSE(INDICIUM)

volumes:
  meltano_postgresql_data:
    driver: local
  meltano_elt_logs_data:
    driver: local

